name: neighbours_yard
description: Final Project by Chakravarty Srinjoy and Thakkar Hardik.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.11-a.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: null
  cloud_firestore: 1.0.5
  cupertino_icons: 1.0.2
  extended_image: 4.0.1
  firebase_auth: 1.0.3
  firebase_core: 1.0.3
  firebase_database: 6.1.2
  firebase_ml_vision: 0.12.0
  firebase_storage: 8.0.3
  flutter_launcher_icons: 0.9.0
  flutter_screenutil: 5.0.0
  fluttertoast: 8.0.3
  geocoder: 0.2.1
  geolocator: 7.0.3
  google_sign_in: 4.5.9
  image_picker: 0.7.4
  location: 4.1.1
  multi_image_picker: 4.8.0
  path: 1.8.0
  path_provider: 2.0.1
  permission_handler: 6.1.1
  transparent_image: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons: null
# image_path: "assets/images/icon-128x128.png"
# image_path_android: "assets/images/icon.png"
# image_path_ios: "assets/images/icon.png"
# android: true # can specify file name here e.g. "ic_launcher"
# ios: true # can specify file name here e.g. "My-Launcher-Icon"
# adaptive_icon_background: "assets/images/icon.png" # only available for Android 8.0 devices and above
# adaptive_icon_foreground: "assets/images/icon.png" # only available for Android 8.0 devices and above
flutter:
  assets:
    - images/
    - assets/
  uses-material-design: true
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  # The following section is specific to Flutter.
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
